name: Bump Meshery or Meshery Extensions UI dependencies
on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: repository
        options: 
        - all
        - meshery
        - meshery-extensions
      dependencies:
        type: choice
        description: dependencies to choose
        options: 
        - react
        - "notistack"
        - "@layer5/sistent"
        - "relay-runtime"
        - "mui-datatables"
        - "@xstate/react"
        - "xstate"
        - "react-json-view"
        - "@reduxjs/toolkit"
        - "react-dom"
        - "axios"
        - "rxjs"
        - "react-redux"
        - "lodash"
        - "js-yaml"
        - "moment"
        - "graphql"
        - "graphql-ws"
        - "uuid"
      version:
        required: true
        type: string
        default: 1.0.0
        description: Version

jobs:
  bump-meshery:
    if: ${{ (github.event.inputs.repository == 'meshery') || (github.event.inputs.repository == 'all') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery code
        uses: actions/checkout@v4
        with:
          repository: meshery/meshery
          fetch-depth: 1
          token: ${{ secrets.RELEASEDRAFTER_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'
      - name: Make changes to pull request
        working-directory: ui
        run: npm install ${{github.event.inputs.dependencies}}@${{ github.event.inputs.version }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RELEASEDRAFTER_PAT }}
          commit-message: Bump ${{github.event.inputs.dependencies}} v${{ github.event.inputs.version }} dependencies
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author:  ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: bump-${{ github.event.inputs.dependencies }}-v${{ github.event.inputs.version }}-bot
          delete-branch: true
          title: '[Chore]: Bump ${{github.event.inputs.dependencies}}'
          add-paths: |
            ui/package.json
            ui/package-lock.json
          body: |
            Update to ${{github.event.inputs.dependencies}} v${{ github.event.inputs.version }}
            
            _This pull request has been auto-generated by [l5io](http://github.com/l5io)_
          assignees: l5io
          draft: false
  bump-meshery-extensions:
    if: ${{ (github.event.inputs.repository == 'meshery-extensions') || (github.event.inputs.repository == 'all') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery Extensions code
        uses: actions/checkout@v4
        with:
          repository: layer5labs/meshery-extensions
          fetch-depth: 1
          token: ${{ secrets.RELEASEDRAFTER_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'
      - name: Make changes to pull request
        working-directory: meshmap
        run: npm install ${{github.event.inputs.dependencies}}@${{ github.event.inputs.version }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RELEASEDRAFTER_PAT }}
          commit-message: Bump ${{github.event.inputs.dependencies}} v${{ github.event.inputs.version }} dependencies
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: bump-${{ github.event.inputs.dependencies }}-v${{ github.event.inputs.version }}-bot
          delete-branch: true
          title: '[Chore]: Bump ${{github.event.inputs.dependencies}}'
          add-paths: |
            meshmap/package.json
            meshmap/package-lock.json
          body: |
            Update to ${{github.event.inputs.dependencies}} v${{ github.event.inputs.version }}
            
            _This pull request has been auto-generated by [l5io](http://github.com/l5io)_
          assignees: l5io
          draft: false