name: Rollout Kanvas
on:
  workflow_call:
    inputs:
      branch: 
        description: Repository branch to build.
        type: string
        default: master
  workflow_dispatch:
    inputs:
      branch: 
        description: Repository branch to build.
        type: string
        default: master
jobs:
  build-and-release:
      name: Build and Rollout Kanvas
      env:
        RELEASE_CHANNEL: "kanvas"
      runs-on: ubuntu-latest 
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: meshery/meshery
          ref: ${{ inputs.branch }}
      
      - name: Fetch `get-meshery-version` script from meshery-extensions.  
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          sparse-checkout: |
            build/get-meshery-version
          sparse-checkout-cone-mode: false
      
      - name: Fetch Meshery version
        run: |
          chmod +x 400 ./meshery-extensions/build/get-meshery-version
          MESHERY_VERSION=$(./meshery-extensions/build/get-meshery-version)
          echo "MESHERY_VERSION=$MESHERY_VERSION" >> $GITHUB_ENV
      
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Meshery UI
        working-directory: './meshery'
        run: |
          cat << EOF > ui/ui.config.js
          module.exports = {
            components: {
              navigator: false, // set false to disable the navigator component ( default: true )
            },
          };
          EOF
          
      - name: Docker build & tag
        working-directory: './meshery'
        run: |
          DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile --no-cache -t layer5/meshery:kanvas-latest --build-arg TOKEN=${{ secrets.GLOBAL_TOKEN }} --build-arg GIT_COMMITSHA=${GITHUB_SHA::8} --build-arg GIT_VERSION=${{ env.MESHERY_VERSION }} --build-arg RELEASE_CHANNEL=${RELEASE_CHANNEL} .

          docker tag layer5/meshery:kanvas-latest layer5/meshery:kanvas-${GITHUB_SHA::8}
          docker tag layer5/meshery:kanvas-latest layer5/meshery:kanvas-${{ env.MESHERY_VERSION }}
     
      - name: Docker push
        run: |
          docker push layer5/meshery:kanvas-latest
          
          docker push layer5/meshery:kanvas-${GITHUB_SHA::8}
          docker push layer5/meshery:kanvas-${{ env.MESHERY_VERSION }}
      
      - name: Rollout Kanvas
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.METAL03_HOST }}
          username: ${{ secrets.METAL03_USERNAME }}
          key: ${{ secrets.METAL03_KEY }}
          port: 22
          script: |
            kubectl set image deployment/meshery meshery=layer5/meshery:kanvas-${{env.MESHERY_VERSION}} -n meshery-extensions
