name: Meshery Extension Test
on:
  release:
    types: [published]
  # pull_request:
  #   paths-ignore:
  #     - 'site/**/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  tests-ui-e2e:
    uses: ./.github/workflows/extension-test-reusable.yml
    secrets: inherit
    with:
      checkout_ref: "master"