name: Pricing List

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: Link of the spreadsheet containing subscription details.
        type: string
        required: true
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch-pricing-list:
    name: Fetch Pricing List
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: layer5io/docs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: List directories
        run: ls -a
        
      - name: Fetch and process pricing list
        uses: ./github/actions/pricing-list-action/
        with:
          spreadsheet_uri: ${{ github.event.inputs.spreadsheet_uri || 'https://docs.google.com/spreadsheets/d/1Ck_5q7U_vLSIDTtplugG3pCVC5zugXgTHtO7T7-yL8g/export?format=csv&gid=0' }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated pricing data
          branch: ${{ github.head_ref || github.ref_name }}
          commit_options: "--signoff"
          file_pattern: 'pricing_data.json'
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>