name: Pricing List

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  fetch-pricing-list:
    name: Fetch Pricing List
    runs-on: ubuntu-latest
    steps:

      # Step 1: Check out the repository to access local files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch and process the pricing list using the local action
      - name: Fetch and process pricing list
        uses: .github/actions/pricing-list-action  # Corrected path (no ./ prefix)
        with:
          spreadsheet_uri: ${{ github.event.inputs.spreadsheet_uri || 'https://docs.google.com/spreadsheets/d/1Ck_5q7U_vLSIDTtplugG3pCVC5zugXgTHtO7T7-yL8g/export?format=csv&gid=0' }}

      # Step 3: Commit the processed pricing data back to the repository
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated pricing data"
          branch: ${{ github.head_ref || github.ref_name }}
          commit_options: "--signoff"
          file_pattern: 'pricing_data.json'
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>