name: Pricing List

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  fetch-pricing-list:
    name: Fetch Pricing List
    runs-on: ubuntu-latest
    steps:

      # Step 1: Check out the repository to access local files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Go (if it's not pre-installed)  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ secrets.GO_VERSION }}

      # Step 3: Set environment variable for spreadsheet URL
      - name: Set spreadsheet URI
        run: |
          echo "INPUT_SPREADSHEET_URI=${{ github.event.inputs.spreadsheet_uri }}" >> $GITHUB_ENV

      # Step 4: Fetch and process the pricing list by directly running the Go file
      - name: Fetch and process pricing list
        run: |
          go mod download  
          go run ./.github/actions/pricing-list-action/main.go

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated pricing data"
          branch: ${{ github.head_ref || github.ref_name }}
          commit_options: "--signoff"
          file_pattern: 'pricing_data.json'
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>