name: Pricing List

on:
  workflow_dispatch:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true
  workflow_call:
    inputs:
      spreadsheet_uri:
        description: 'Link of the spreadsheet containing subscription details.'
        type: string
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true
      GO_VERSION:
        required: true


jobs:
  fetch-pricing-list:
    name: Fetch Pricing List
    runs-on: ubuntu-latest
    steps:

      # Step 1: Check out the repository to access local files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Go (if it's not pre-installed)  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ secrets.GO_VERSION }}

      # Step 3: Set environment variable for spreadsheet URL
      - name: Set spreadsheet URI
        run: |
          if [ -n "${{ inputs.spreadsheet_uri }}" ]; then
            echo "INPUT_SPREADSHEET_URI=${{ inputs.spreadsheet_uri }}" >> $GITHUB_ENV
          else
            echo "INPUT_SPREADSHEET_URI=https://docs.google.com/spreadsheets/d/e/2PACX-1vQwzrUSKfuSRcpkp7sJTw1cSB63s4HCjYLJeGPWECsvqn222hjaaONQlN4X8auKvlaB0es3BqV5rQyz/pub?gid=829069645&single=true&output=csv" >> $GITHUB_ENV
          fi

      # Step 4: Fetch and process the pricing list by directly running the Go file
      - name: Fetch and process pricing list
        run: |
          go run ./.github/actions/pricing-list-action/main.go

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated pricing data"
          branch: master
          commit_options: "--signoff"
          file_pattern: 'pricing_data.json'
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>