name: Production Smoke Test
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
        default: 'kanvas'
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: environment to choose
        options: 
        - kanvas
        - playground

jobs:
  smoke-test-kanvas:
    name: Kanvas end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery-extensions code
        uses: actions/checkout@v4
        with:
          repository: layer5labs/meshery-extensions
          path: ./meshery-extensions
          fetch-depth: 1
          ref: "master"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: 'meshery-extensions/meshmap/package-lock.json'
      - name: Install Meshery Extension dependencies
        working-directory: meshery-extensions
        run: cd meshmap; npm ci; cd ../

      - name: show tree
        run: tree  -L 2

      - name: Install Playwright dependencies
        working-directory: meshery-extensions
        run: ls && make test-setup
      - name: Run  Tests
        id: run_tests
        working-directory: meshery-extensions
        run: |
          cd meshmap; test-smoke-${{github.event.inputs.project}}; cd ../
        env:
          REMOTE_PROVIDER_USER_EMAIL: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_EMAIL }}
          REMOTE_PROVIDER_USER_PASSWORD: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_PASSWORD }}