name: Meshery Cloud Build On PR Dispatch
on:
  workflow_dispatch:
    inputs:
      pr_commit_sha:
        required: true
        type: string
      pr_number:
        required: true
        type: number

jobs:
  pass-secrets-to-workflow:
    uses: ./.github/workflows/meshery-cloud-build-reusable.yml
    secrets: inherit
    with:
      pr_commit_sha: ${{inputs.pr_commit_sha}}
      pr_number: ${{inputs.pr_number}}