name: Production Smoke Test
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

jobs:
  smoke-test-production:
    name: Production end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshery-extensions code
        uses: actions/checkout@v4
        with:
          repository: layer5labs/meshery-extensions
          path: ./meshery-extensions
          fetch-depth: 1
          ref: "master"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: 'meshery-extensions/meshmap/package-lock.json'
      - name: show tree
        run: tree  -L 2
      - name: Install Playwright dependencies
        working-directory: meshery-extensions
        run: ls && make test-setup
      - name: Run  Tests
        id: run_tests
        working-directory: meshery-extensions
        run: make test-smoke-${{github.event.inputs.project}}
        env:
          REMOTE_PROVIDER_USER_EMAIL: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_EMAIL }}
          REMOTE_PROVIDER_USER_PASSWORD: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_PASSWORD }}
      # - name: Send Email on Production Release Failure
      #   if: ${{ failure() }}
      #   uses: dawidd6/action-send-mail@v3.7.1
      #   env:
      #     msg: ${{ github.event.inputs.project }} Production Failure
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: GitHub Actions - Production Release Failure
      #     from: |
      #       "Meshery Extensions" <no-reply@meshery.io>
      #     to: |
      #       "Layer5 Support" <support@layer5.io>
      #     html_body: |
      #       <b>REPO:</b> ${{ github.repository }}<br />  
      #       <b>WORKFLOW:</b> ${{ github.workflow }}<br />
      #       <b>JOB:</b> ${{ github.job }}<br />
      #       <b>REASON:</b> ${{ env.msg }}<br />
      #       <b>DETAILS:</b> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}${{ job.status }}">${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}</a><br />